from __future__ import annotations


ANNOTATION_VERSION = "scd-codebook-2024-1-v1"
DOI_VERSION = "10.5281/zenodo.11092977"

SCD_COLUMNS = [
    "docref",
    "url",
    "date",
    "year",
    "proc_type",
    "merged_cases",
    "division",
    "division_type",
    "n_judges",
    "language",
    "length",
    "area_general",
    "area_intermediate",
    "area_detailed",
    "topic",
    "issue",
    "source_date",
    "source_canton",
    "proc_duration",
    "app_class",
    "app_represented",
    "resp_class",
    "resp_represented",
    "outcome",
    "outcome_binary",
    "cited_bger",
    "n_cited_bger",
    "cited_bge",
    "n_cited_bge",
    "leading_case",
    "doi_version",
]

PROC_TYPE_BY_LETTER = {
    "A": "Civil",
    "B": "Criminal",
    "C": "Public",
    "D": "Constitutional",
    "E": "Action",
    "F": "Revision",
    "G": "Correction",
}

CANTON_PATTERNS = {
    "ZH": ("zürich", "zurich"),
    "BE": ("bern", "berne"),
    "LU": ("luzern", "lucerne"),
    "UR": ("uri",),
    "SZ": ("schwyz",),
    "OW": ("obwalden",),
    "NW": ("nidwalden",),
    "GL": ("glarus",),
    "ZG": ("zug",),
    "FR": ("freiburg", "fribourg"),
    "SO": ("solothurn", "soleure"),
    "BS": ("basel-stadt", "bâle-ville", "basilea-città"),
    "BL": ("basel-landschaft", "bâle-campagne", "basilea-campagna"),
    "SH": ("schaffhausen",),
    "AR": ("appenzell ausserrhoden", "appenzell rhodes-extérieures"),
    "AI": ("appenzell innerrhoden", "appenzell rhodes-intérieures"),
    "SG": ("st. gallen", "st. gall", "saint-gall", "san gallo"),
    "GR": ("graubünden", "grisons", "grigioni"),
    "AG": ("aargau", "argovie"),
    "TG": ("thurgau", "thurgovie", "turgovia"),
    "TI": ("ticino", "tessin"),
    "VD": ("vaud",),
    "VS": ("wallis", "valais"),
    "NE": ("neuchâtel", "neuenburg"),
    "GE": ("genève", "geneva", "genf", "ginevra"),
    "JU": ("jura",),
}

FEDERAL_SOURCE_PATTERNS = (
    "bundesverwaltungsgericht",
    "bundesstrafgericht",
    "bundespatentgericht",
    "tribunal administratif fédéral",
    "tribunal pénal fédéral",
    "tribunale amministrativo federale",
    "tribunale penale federale",
)

MONTHS = {
    "januar": 1,
    "janvier": 1,
    "gennaio": 1,
    "februar": 2,
    "février": 2,
    "fevrier": 2,
    "febbraio": 2,
    "märz": 3,
    "maerz": 3,
    "mars": 3,
    "marzo": 3,
    "april": 4,
    "avril": 4,
    "aprile": 4,
    "mai": 5,
    "maggio": 5,
    "juni": 6,
    "juin": 6,
    "giugno": 6,
    "juli": 7,
    "juillet": 7,
    "luglio": 7,
    "august": 8,
    "août": 8,
    "aout": 8,
    "agosto": 8,
    "september": 9,
    "septembre": 9,
    "settembre": 9,
    "oktober": 10,
    "octobre": 10,
    "ottobre": 10,
    "november": 11,
    "novembre": 11,
    "dezember": 12,
    "décembre": 12,
    "decembre": 12,
    "dicembre": 12,
}

COMMON_AREA_KEYWORDS = {
    "Berufliche Vorsorge": ("berufliche vorsorge", "bvg", "prévoyance professionnelle"),
    "Invalidenversicherung": ("invalidenversicherung", "iv-stelle", "assurance-invalidité"),
    "Alters- und Hinterlassenenversicherung": (
        "alters- und hinterlassenenversicherung",
        "ahv",
        "avs",
        "assurance-vieillesse",
    ),
    "Ergänzungsleistung": (
        "ergänzungsleistung",
        "prestations complémentaires",
        "prestazione complementare",
    ),
    "Unfallversicherung": ("unfallversicherung", "suva", "assurance-accidents"),
    "Krankenversicherung": ("krankenversicherung", "assurance-maladie"),
    "Arbeitslosenversicherung": ("arbeitslosenversicherung", "assurance-chômage"),
    "Bürgerrecht und Ausländerrecht": (
        "aufenthaltsbewilligung",
        "niederlassungsbewilligung",
        "ausländerrecht",
        "permesso di dimora",
        "autorisation de séjour",
        "autorisation d'établissement",
        "regroupement familial",
        "droit des étrangers",
        "naturalisation",
        "einbürgerung",
    ),
    "Schuldbetreibungs- und Konkursrecht": (
        "schuldbetreibung",
        "konkurs",
        "poursuite",
        "faillite",
        "mainlevée",
        "rechtsöffnung",
    ),
    "Strafprozess": (
        "strafprozess",
        "strafverfahren",
        "untersuchungshaft",
        "beschlagnahme",
        "procédure pénale",
        "détention provisoire",
        "détention pour des motifs de sûreté",
        "séquestre",
    ),
    "Strafrecht (allgemein)": (
        "strafrecht (allgemein)",
        "allgemeiner teil des strafrechts",
    ),
    "Straftaten": (
        "stgb",
        "strafrecht",
        "infraction",
        "reato",
        "lcr",
        "irreführung der rechtspflege",
        "geldwäscherei",
        "urkundenfälschung",
    ),
    "Familienrecht": (
        "ehescheidung",
        "eheschutz",
        "eheliche gemeinschaft",
        "kindesschutz",
        "unterhalt",
        "autorité parentale",
        "divorce",
        "mesures protectrices de l'union conjugale",
        "union conjugale",
    ),
    "Sachenrecht": ("sachenrecht", "dienstbarkeit", "servitude", "propriété"),
    "Obligationenrecht (allgemein)": ("obligationenrecht", "responsabilité civile"),
    "Vertragsrecht": (
        "vertrag",
        "contrat",
        "contratto",
        "arbeitsvertrag",
        "contrat de travail",
        "licenciement",
        "mietvertrag",
        "bail",
    ),
    "Raumplanung und öffentliches Baurecht": (
        "baubewilligung",
        "raumplanung",
        "permis de construire",
        "aménagement du territoire",
        "construction",
        "baugesuch",
    ),
    "Öffentliche Finanzen und Abgaberecht": ("steuer", "impôt", "tassa"),
    "Gesundheitswesen und soziale Sicherheit": (
        "gesundheitswesen",
        "santé publique",
        "soziale sicherheit",
    ),
    "Grundrecht": ("grundrecht", "droits fondamentaux", "liberté personnelle"),
    "Strassenbau und Strassenverkehr": (
        "strassenverkehr",
        "strassenbau",
        "circulation routière",
        "permis de conduire",
    ),
    "Öffentliches Dienstverhältnis": (
        "öffentliches dienstverhältnis",
        "fonction publique",
        "rapports de service",
    ),
    "Unterrichtswesen und Berufsausbildung": (
        "unterrichtswesen",
        "berufsausbildung",
        "formation professionnelle",
        "école",
    ),
    "Politische Rechte": ("politische rechte", "droits politiques", "votation"),
}

AREA_AGGREGATION = {
    "Berufliche Vorsorge": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Invalidenversicherung": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Unfallversicherung": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Krankenversicherung": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Arbeitslosenversicherung": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Alters- und Hinterlassenenversicherung": (
        "Sozialversicherungsrecht",
        "Öffentliches Recht",
    ),
    "Ergänzungsleistung": ("Sozialversicherungsrecht", "Öffentliches Recht"),
    "Bürgerrecht und Ausländerrecht": ("Bürgerrecht und Ausländerrecht", "Öffentliches Recht"),
    "Schuldbetreibungs- und Konkursrecht": (
        "Schuldbetreibungs- und Konkursrecht",
        "Öffentliches Recht",
    ),
    "Strafprozess": ("Strafprozess", "Strafrecht"),
    "Strafrecht (allgemein)": ("Strafrecht", "Strafrecht"),
    "Straftaten": ("Strafrecht", "Strafrecht"),
    "Familienrecht": ("Zivilrecht", "Privatrecht"),
    "Sachenrecht": ("Zivilrecht", "Privatrecht"),
    "Obligationenrecht (allgemein)": ("Obligationenrecht und Handelsrecht", "Privatrecht"),
    "Vertragsrecht": ("Obligationenrecht und Handelsrecht", "Privatrecht"),
    "Raumplanung und öffentliches Baurecht": (
        "Raumplanung und öffentliches Baurecht",
        "Öffentliches Recht",
    ),
    "Öffentliche Finanzen und Abgaberecht": (
        "Öffentliche Finanzen und Abgaberecht",
        "Öffentliches Recht",
    ),
    "Gesundheitswesen und soziale Sicherheit": (
        "Gesundheitswesen und soziale Sicherheit",
        "Öffentliches Recht",
    ),
    "Grundrecht": ("Grundrecht", "Öffentliches Recht"),
    "Strassenbau und Strassenverkehr": (
        "Strassenbau und Strassenverkehr",
        "Öffentliches Recht",
    ),
    "Öffentliches Dienstverhältnis": (
        "Öffentliches Dienstverhältnis",
        "Öffentliches Recht",
    ),
    "Unterrichtswesen und Berufsausbildung": (
        "Unterrichtswesen und Berufsausbildung",
        "Öffentliches Recht",
    ),
    "Politische Rechte": ("Politische Rechte", "Öffentliches Recht"),
}
